version: '3'
services:
  log:
    build: .
    ports:
      - "8080:8080"
    container_name: "logsvc"
    environment:
      LOGSVC_SERVER_ADDR: ":8080"
      LOGSVC_DATABASE_ADDR: "postgres:5432"
      LOGSVC_DATABASE_USER: "postgres"
      LOGSVC_DATABASE_PASSWORD: "mypostgrespw"
      LOGSVC_DATABASE_NAME: "postgres"
  postgres:
    image: "postgres:10"
    container_name: "postgres-for-logsvc"
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: "mypostgrespw"
